spring:
  profiles:
    active:
     - dev

---
spring:
  profiles: dev
  port: 8080
  application:
    name: microservicecloud-config-atguigu-dev

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-atguigu-test
