spring:
  profiles:
    active:
     - dev

---
server:
  port: 8088
spring:
  profiles: dev
  port: 8080
  application:
    name: application

---
server:
  port: 8089
spring:
  profiles: test
  application:
    name: microservicecloud-config-atguigu-test
